export const { dirname, extname } = await import("https://cdn.deno.land/std/versions/0.189.0/raw/path/mod.ts")
export const { red, green } = await import("https://cdn.deno.land/std/versions/0.189.0/raw/fmt/colors.ts")
export const { exists } = await import("https://cdn.deno.land/std/versions/0.189.0/raw/fs/exists.ts")
export const { serve, serveTls } = await import("https://deno.land/std@0.189.0/http/server.ts")
export const { sassCompiler, tsCompiler } = await import("https://raw.githubusercontent.com/dragos-tudor/frontend-building/v0.1.0/index.js")